import './globals.css'
import type { Metadata } from 'next'
import NavBar from './nav/NavBar'

export const metadata: Metadata = {
  title: 'Bidding App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className='container mx-auto px-5 pt-10'>
          {children}
        </main> 
      </body>
    </html>
  )
}
